
"""Notification for when an episode of anime airs"""
type AiringNotification {
  """The id of the aired anime"""
  animeId: Int!

  """The notification context text"""
  contexts: [String]

  """The time the notification was created at"""
  createdAt: Int

  """The episode number that just aired"""
  episode: Int!

  """The id of the Notification"""
  id: Int!

  """The associated media of the airing schedule"""
  media: Media

  """The type of notification"""
  type: NotificationType
}

"""Score & Watcher stats for airing anime by episode and mid-week"""
type AiringProgression {
  """
  The episode the stats were recorded at. .5 is the mid point between 2 episodes airing dates.
  """
  episode: Float

  """The average score for the media"""
  score: Float

  """The amount of users watching the anime"""
  watching: Int
}

"""
Media Airing Schedule. NOTE: We only aim to guarantee that FUTURE airing data is present and accurate.
"""
type AiringSchedule {
  """The time the episode airs at"""
  airingAt: Int!

  """The airing episode number"""
  episode: Int!

  """The id of the airing schedule item"""
  id: Int!

  """The associate media of the airing episode"""
  media: Media

  """The associate media id of the airing episode"""
  mediaId: Int!

  """Seconds until episode starts airing"""
  timeUntilAiring: Int!
}

type AiringScheduleConnection {
  edges: [AiringScheduleEdge]
  nodes: [AiringSchedule]

  """The pagination information"""
  pageInfo: PageInfo
}

"""AiringSchedule connection edge"""
type AiringScheduleEdge {
  """The id of the connection"""
  id: Int
  node: AiringSchedule
}

input AiringScheduleInput {
  airingAt: Int
  episode: Int
  timeUntilAiring: Int
}

"""Airing schedule sort enums"""
enum AiringSort {
  ID
  ID_DESC
  MEDIA_ID
  MEDIA_ID_DESC
  TIME
  TIME_DESC
  EPISODE
  EPISODE_DESC
}
