
"""A character that features in an anime or manga"""
type Character {
  """
  The character's age. Note this is a string, not an int, it may contain further text and additional ages.
  """
  age: String

  """The characters blood type"""
  bloodType: String

  """The character's birth date"""
  dateOfBirth: FuzzyDate

  """A general description of the character"""
  description(
    """Return the string in pre-parsed html instead of markdown"""
    asHtml: Boolean
  ): String

  """The amount of user's who have favourited the character"""
  favourites: Int

  """
  The character's gender. Usually Male, Female, or Non-binary but can be any string.
  """
  gender: String

  """The id of the character"""
  id: Int!

  """Character images"""
  image: CharacterImage

  """
  If the character is marked as favourite by the currently authenticated user
  """
  isFavourite: Boolean!

  """If the character is blocked from being added to favourites"""
  isFavouriteBlocked: Boolean!

  """Media that includes the character"""
  media(
    onList: Boolean

    """The page"""
    page: Int

    """The amount of entries per page, max 25"""
    perPage: Int
    sort: [MediaSort]
    type: MediaType
  ): MediaConnection

  """Notes for site moderators"""
  modNotes: String

  """The names of the character"""
  name: CharacterName

  """The url for the character page on the AniList website"""
  siteUrl: String
  updatedAt: Int @deprecated(reason: "No data available")
}

type CharacterConnection {
  edges: [CharacterEdge]
  nodes: [Character]

  """The pagination information"""
  pageInfo: PageInfo
}

"""Character connection edge"""
type CharacterEdge {
  """The order the character should be displayed from the users favourites"""
  favouriteOrder: Int

  """The id of the connection"""
  id: Int

  """The media the character is in"""
  media: [Media]

  """Media specific character name"""
  name: String
  node: Character

  """The characters role in the media"""
  role: CharacterRole

  """The voice actors of the character with role date"""
  voiceActorRoles(language: StaffLanguage, sort: [StaffSort]): [StaffRoleType]

  """The voice actors of the character"""
  voiceActors(language: StaffLanguage, sort: [StaffSort]): [Staff]
}

type CharacterImage {
  """The character's image of media at its largest size"""
  large: String

  """The character's image of media at medium size"""
  medium: String
}

"""The names of the character"""
type CharacterName {
  """Other names the character might be referred to as"""
  alternative: [String]

  """Other names the character might be referred to as but are spoilers"""
  alternativeSpoiler: [String]

  """The character's given name"""
  first: String

  """The character's first and last name"""
  full: String

  """The character's surname"""
  last: String

  """The character's middle name"""
  middle: String

  """The character's full name in their native language"""
  native: String

  """
  The currently authenticated users preferred name language. Default romaji for non-authenticated
  """
  userPreferred: String
}

"""The names of the character"""
input CharacterNameInput {
  """Other names the character might be referred by"""
  alternative: [String]

  """Other names the character might be referred to as but are spoilers"""
  alternativeSpoiler: [String]

  """The character's given name"""
  first: String

  """The character's surname"""
  last: String

  """The character's middle name"""
  middle: String

  """The character's full name in their native language"""
  native: String
}

"""The role the character plays in the media"""
enum CharacterRole {
  """A primary character role in the media"""
  MAIN

  """A supporting character role in the media"""
  SUPPORTING

  """A background character in the media"""
  BACKGROUND
}

"""Character sort enums"""
enum CharacterSort {
  ID
  ID_DESC
  ROLE
  ROLE_DESC
  SEARCH_MATCH
  FAVOURITES
  FAVOURITES_DESC

  """Order manually decided by moderators"""
  RELEVANCE
}

"""A submission for a character that features in an anime or manga"""
type CharacterSubmission {
  """Data Mod assigned to handle the submission"""
  assignee: User

  """Character that the submission is referencing"""
  character: Character
  createdAt: Int

  """The id of the submission"""
  id: Int!

  """Whether the submission is locked"""
  locked: Boolean

  """Inner details of submission status"""
  notes: String
  source: String

  """Status of the submission"""
  status: SubmissionStatus

  """The character submission changes"""
  submission: Character

  """Submitter for the submission"""
  submitter: User
}

type CharacterSubmissionConnection {
  edges: [CharacterSubmissionEdge]
  nodes: [CharacterSubmission]

  """The pagination information"""
  pageInfo: PageInfo
}

"""CharacterSubmission connection edge"""
type CharacterSubmissionEdge {
  node: CharacterSubmission

  """The characters role in the media"""
  role: CharacterRole

  """The submitted voice actors of the character"""
  submittedVoiceActors: [StaffSubmission]

  """The voice actors of the character"""
  voiceActors: [Staff]
}
