
"""Types that can be liked"""
enum LikeableType {
  THREAD
  THREAD_COMMENT
  ACTIVITY
  ACTIVITY_REPLY
}

"""Likeable union type"""
union LikeableUnion = ListActivity | TextActivity | MessageActivity | ActivityReply | Thread | ThreadComment
