
"""Media recommendation"""
type Recommendation {
  """The id of the recommendation"""
  id: Int!

  """The media the recommendation is from"""
  media: Media

  """The recommended media"""
  mediaRecommendation: Media

  """Users rating of the recommendation"""
  rating: Int

  """The user that first created the recommendation"""
  user: User

  """The rating of the recommendation by currently authenticated user"""
  userRating: RecommendationRating
}

type RecommendationConnection {
  edges: [RecommendationEdge]
  nodes: [Recommendation]

  """The pagination information"""
  pageInfo: PageInfo
}

"""Recommendation connection edge"""
type RecommendationEdge {
  node: Recommendation
}

"""Recommendation rating enums"""
enum RecommendationRating {
  NO_RATING
  RATE_UP
  RATE_DOWN
}

"""Recommendation sort enums"""
enum RecommendationSort {
  ID
  ID_DESC
  RATING
  RATING_DESC
}
