
"""A Review that features in an anime or manga"""
type Review {
  """The main review body text"""
  body(
    """Return the string in pre-parsed html instead of markdown"""
    asHtml: Boolean
  ): String

  """The time of the thread creation"""
  createdAt: Int!

  """The id of the review"""
  id: Int!

  """The media the review is of"""
  media: Media

  """The id of the review's media"""
  mediaId: Int!

  """For which type of media the review is for"""
  mediaType: MediaType

  """
  If the review is not yet publicly published and is only viewable by creator
  """
  private: Boolean

  """The total user rating of the review"""
  rating: Int

  """The amount of user ratings of the review"""
  ratingAmount: Int

  """The review score of the media"""
  score: Int

  """The url for the review page on the AniList website"""
  siteUrl: String

  """A short summary of the review"""
  summary: String

  """The time of the thread last update"""
  updatedAt: Int!

  """The creator of the review"""
  user: User

  """The id of the review's creator"""
  userId: Int!

  """The rating of the review by currently authenticated user"""
  userRating: ReviewRating
}

type ReviewConnection {
  edges: [ReviewEdge]
  nodes: [Review]

  """The pagination information"""
  pageInfo: PageInfo
}

"""Review connection edge"""
type ReviewEdge {
  node: Review
}

"""Review rating enums"""
enum ReviewRating {
  NO_VOTE
  UP_VOTE
  DOWN_VOTE
}

"""Review sort enums"""
enum ReviewSort {
  ID
  ID_DESC
  SCORE
  SCORE_DESC
  RATING
  RATING_DESC
  CREATED_AT
  CREATED_AT_DESC
  UPDATED_AT
  UPDATED_AT_DESC
}
