
type SiteStatistics {
  anime(
    """The page"""
    page: Int

    """The amount of entries per page, max 25"""
    perPage: Int
    sort: [SiteTrendSort]
  ): SiteTrendConnection
  characters(
    """The page"""
    page: Int

    """The amount of entries per page, max 25"""
    perPage: Int
    sort: [SiteTrendSort]
  ): SiteTrendConnection
  manga(
    """The page"""
    page: Int

    """The amount of entries per page, max 25"""
    perPage: Int
    sort: [SiteTrendSort]
  ): SiteTrendConnection
  reviews(
    """The page"""
    page: Int

    """The amount of entries per page, max 25"""
    perPage: Int
    sort: [SiteTrendSort]
  ): SiteTrendConnection
  staff(
    """The page"""
    page: Int

    """The amount of entries per page, max 25"""
    perPage: Int
    sort: [SiteTrendSort]
  ): SiteTrendConnection
  studios(
    """The page"""
    page: Int

    """The amount of entries per page, max 25"""
    perPage: Int
    sort: [SiteTrendSort]
  ): SiteTrendConnection
  users(
    """The page"""
    page: Int

    """The amount of entries per page, max 25"""
    perPage: Int
    sort: [SiteTrendSort]
  ): SiteTrendConnection
}

"""Daily site statistics"""
type SiteTrend {
  """The change from yesterday"""
  change: Int!
  count: Int!

  """The day the data was recorded (timestamp)"""
  date: Int!
}

type SiteTrendConnection {
  edges: [SiteTrendEdge]
  nodes: [SiteTrend]

  """The pagination information"""
  pageInfo: PageInfo
}

"""Site trend connection edge"""
type SiteTrendEdge {
  node: SiteTrend
}

"""Site trend sort enums"""
enum SiteTrendSort {
  DATE
  DATE_DESC
  COUNT
  COUNT_DESC
  CHANGE
  CHANGE_DESC
}
