
"""Animation or production company"""
type Studio {
  """The amount of user's who have favourited the studio"""
  favourites: Int

  """The id of the studio"""
  id: Int!

  """If the studio is an animation studio or a different kind of company"""
  isAnimationStudio: Boolean!

  """
  If the studio is marked as favourite by the currently authenticated user
  """
  isFavourite: Boolean!

  """The media the studio has worked on"""
  media(
    """If the studio was the primary animation studio of the media"""
    isMain: Boolean
    onList: Boolean

    """The page"""
    page: Int

    """The amount of entries per page, max 25"""
    perPage: Int

    """The order the results will be returned in"""
    sort: [MediaSort]
  ): MediaConnection

  """The name of the studio"""
  name: String!

  """The url for the studio page on the AniList website"""
  siteUrl: String
}

type StudioConnection {
  edges: [StudioEdge]
  nodes: [Studio]

  """The pagination information"""
  pageInfo: PageInfo
}

"""Studio connection edge"""
type StudioEdge {
  """The order the character should be displayed from the users favourites"""
  favouriteOrder: Int

  """The id of the connection"""
  id: Int

  """If the studio is the main animation studio of the anime"""
  isMain: Boolean!
  node: Studio
}

"""Studio sort enums"""
enum StudioSort {
  ID
  ID_DESC
  NAME
  NAME_DESC
  SEARCH_MATCH
  FAVOURITES
  FAVOURITES_DESC
}

"""User's studio statistics"""
type StudioStats {
  amount: Int
  meanScore: Int
  studio: Studio

  """
  The amount of time in minutes the studio's works have been watched by the user
  """
  timeWatched: Int
}

"""Animation or production company"""
type Studio {
  """The amount of user's who have favourited the studio"""
  favourites: Int

  """The id of the studio"""
  id: Int!

  """If the studio is an animation studio or a different kind of company"""
  isAnimationStudio: Boolean!

  """
  If the studio is marked as favourite by the currently authenticated user
  """
  isFavourite: Boolean!

  """The media the studio has worked on"""
  media(
    """If the studio was the primary animation studio of the media"""
    isMain: Boolean
    onList: Boolean

    """The page"""
    page: Int

    """The amount of entries per page, max 25"""
    perPage: Int

    """The order the results will be returned in"""
    sort: [MediaSort]
  ): MediaConnection

  """The name of the studio"""
  name: String!

  """The url for the studio page on the AniList website"""
  siteUrl: String
}

type StudioConnection {
  edges: [StudioEdge]
  nodes: [Studio]

  """The pagination information"""
  pageInfo: PageInfo
}

"""Studio connection edge"""
type StudioEdge {
  """The order the character should be displayed from the users favourites"""
  favouriteOrder: Int

  """The id of the connection"""
  id: Int

  """If the studio is the main animation studio of the anime"""
  isMain: Boolean!
  node: Studio
}

"""Studio sort enums"""
enum StudioSort {
  ID
  ID_DESC
  NAME
  NAME_DESC
  SEARCH_MATCH
  FAVOURITES
  FAVOURITES_DESC
}

"""User's studio statistics"""
type StudioStats {
  amount: Int
  meanScore: Int
  studio: Studio

  """
  The amount of time in minutes the studio's works have been watched by the user
  """
  timeWatched: Int
}
