
"""Forum Thread"""
type Thread {
  """The text body of the thread (Markdown)"""
  body(
    """Return the string in pre-parsed html instead of markdown"""
    asHtml: Boolean
  ): String

  """The categories of the thread"""
  categories: [ThreadCategory]

  """The time of the thread creation"""
  createdAt: Int!

  """The id of the thread"""
  id: Int!

  """If the currently authenticated user liked the thread"""
  isLiked: Boolean

  """If the thread is locked and can receive comments"""
  isLocked: Boolean

  """
  If the thread is stickied and should be displayed at the top of the page
  """
  isSticky: Boolean

  """If the currently authenticated user is subscribed to the thread"""
  isSubscribed: Boolean

  """The amount of likes the thread has"""
  likeCount: Int!

  """The users who liked the thread"""
  likes: [User]

  """The media categories of the thread"""
  mediaCategories: [Media]

  """The time of the last reply"""
  repliedAt: Int

  """The id of the most recent comment on the thread"""
  replyCommentId: Int

  """The number of comments on the thread"""
  replyCount: Int

  """The user to last reply to the thread"""
  replyUser: User

  """The id of the user who most recently commented on the thread"""
  replyUserId: Int

  """The url for the thread page on the AniList website"""
  siteUrl: String

  """The title of the thread"""
  title: String

  """The time of the thread last update"""
  updatedAt: Int!

  """The owner of the thread"""
  user: User

  """The id of the thread owner user"""
  userId: Int!

  """The number of times users have viewed the thread"""
  viewCount: Int
}

"""A forum thread category"""
type ThreadCategory {
  """The id of the category"""
  id: Int!

  """The name of the category"""
  name: String!
}

"""Forum Thread Comment"""
type ThreadComment {
  """The comment's child reply comments"""
  childComments: Json

  """The text content of the comment (Markdown)"""
  comment(
    """Return the string in pre-parsed html instead of markdown"""
    asHtml: Boolean
  ): String

  """The time of the comments creation"""
  createdAt: Int!

  """The id of the comment"""
  id: Int!

  """If the currently authenticated user liked the comment"""
  isLiked: Boolean

  """If the comment tree is locked and may not receive replies or edits"""
  isLocked: Boolean

  """The amount of likes the comment has"""
  likeCount: Int!

  """The users who liked the comment"""
  likes: [User]

  """The url for the comment page on the AniList website"""
  siteUrl: String

  """The thread the comment belongs to"""
  thread: Thread

  """The id of thread the comment belongs to"""
  threadId: Int

  """The time of the comments last update"""
  updatedAt: Int!

  """The user who created the comment"""
  user: User

  """The user id of the comment's owner"""
  userId: Int
}

"""Notification for when a thread comment is liked"""
type ThreadCommentLikeNotification {
  """The thread comment that was liked"""
  comment: ThreadComment

  """The id of the activity which was liked"""
  commentId: Int!

  """The notification context text"""
  context: String

  """The time the notification was created at"""
  createdAt: Int

  """The id of the Notification"""
  id: Int!

  """The thread that the relevant comment belongs to"""
  thread: Thread

  """The type of notification"""
  type: NotificationType

  """The user who liked the activity"""
  user: User

  """The id of the user who liked to the activity"""
  userId: Int!
}

"""
Notification for when authenticated user is @ mentioned in a forum thread comment
"""
type ThreadCommentMentionNotification {
  """The thread comment that included the @ mention"""
  comment: ThreadComment

  """The id of the comment where mentioned"""
  commentId: Int!

  """The notification context text"""
  context: String

  """The time the notification was created at"""
  createdAt: Int

  """The id of the Notification"""
  id: Int!

  """The thread that the relevant comment belongs to"""
  thread: Thread

  """The type of notification"""
  type: NotificationType

  """The user who mentioned the authenticated user"""
  user: User

  """The id of the user who mentioned the authenticated user"""
  userId: Int!
}

"""Notification for when a user replies to your forum thread comment"""
type ThreadCommentReplyNotification {
  """The reply thread comment"""
  comment: ThreadComment

  """The id of the reply comment"""
  commentId: Int!

  """The notification context text"""
  context: String

  """The time the notification was created at"""
  createdAt: Int

  """The id of the Notification"""
  id: Int!

  """The thread that the relevant comment belongs to"""
  thread: Thread

  """The type of notification"""
  type: NotificationType

  """The user who replied to the activity"""
  user: User

  """The id of the user who create the comment reply"""
  userId: Int!
}

"""Thread comments sort enums"""
enum ThreadCommentSort {
  ID
  ID_DESC
}

"""Notification for when a user replies to a subscribed forum thread"""
type ThreadCommentSubscribedNotification {
  """The reply thread comment"""
  comment: ThreadComment

  """The id of the new comment in the subscribed thread"""
  commentId: Int!

  """The notification context text"""
  context: String

  """The time the notification was created at"""
  createdAt: Int

  """The id of the Notification"""
  id: Int!

  """The thread that the relevant comment belongs to"""
  thread: Thread

  """The type of notification"""
  type: NotificationType

  """The user who replied to the subscribed thread"""
  user: User

  """The id of the user who commented on the thread"""
  userId: Int!
}

"""Notification for when a thread is liked"""
type ThreadLikeNotification {
  """The liked thread comment"""
  comment: ThreadComment

  """The notification context text"""
  context: String

  """The time the notification was created at"""
  createdAt: Int

  """The id of the Notification"""
  id: Int!

  """The thread that the relevant comment belongs to"""
  thread: Thread

  """The id of the thread which was liked"""
  threadId: Int!

  """The type of notification"""
  type: NotificationType

  """The user who liked the activity"""
  user: User

  """The id of the user who liked to the activity"""
  userId: Int!
}

"""Thread sort enums"""
enum ThreadSort {
  ID
  ID_DESC
  TITLE
  TITLE_DESC
  CREATED_AT
  CREATED_AT_DESC
  UPDATED_AT
  UPDATED_AT_DESC
  REPLIED_AT
  REPLIED_AT_DESC
  REPLY_COUNT
  REPLY_COUNT_DESC
  VIEW_COUNT
  VIEW_COUNT_DESC
  IS_STICKY
  SEARCH_MATCH
}
